-- Cash lifecycle, controls, bank deposits, workflows and accounting mapping.

CREATE TABLE llx_sof_caisse_cloture (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_session integer NOT NULL,
  fk_agence integer NOT NULL,
  fk_caisse integer NOT NULL,
  date_cloture datetime NOT NULL,
  total_cash double(24,8) DEFAULT 0,
  total_card double(24,8) DEFAULT 0,
  total_cheque double(24,8) DEFAULT 0,
  total_transfer double(24,8) DEFAULT 0,
  total_mobile_money double(24,8) DEFAULT 0,
  total_deferred double(24,8) DEFAULT 0,
  total_refund double(24,8) DEFAULT 0,
  total_credit_note double(24,8) DEFAULT 0,
  theoretical_amount double(24,8) DEFAULT 0,
  physical_amount double(24,8) DEFAULT 0,
  gap_amount double(24,8) DEFAULT 0,
  cashier_comment text,
  validator_comment text,
  fk_user_cashier integer,
  fk_user_validator integer,
  status integer DEFAULT 0 NOT NULL,
  report_ref varchar(255),
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_caisse_comptage (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_session integer NOT NULL,
  fk_cloture integer,
  fk_controle integer,
  currency_code varchar(10),
  denomination_value double(24,8) NOT NULL,
  quantity integer DEFAULT 0 NOT NULL,
  amount double(24,8) DEFAULT 0 NOT NULL,
  comptage_type varchar(64) DEFAULT 'closing',
  status integer DEFAULT 1 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_caisse_ecart (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_session integer NOT NULL,
  fk_cloture integer,
  fk_controle integer,
  fk_agence integer NOT NULL,
  fk_caisse integer NOT NULL,
  gap_type varchar(64) NOT NULL,
  theoretical_amount double(24,8) DEFAULT 0,
  physical_amount double(24,8) DEFAULT 0,
  gap_amount double(24,8) DEFAULT 0,
  severity varchar(64),
  reason text,
  treatment_decision text,
  date_treatment datetime,
  fk_user_cashier integer,
  fk_user_validator integer,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_caisse_controle (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_agence integer NOT NULL,
  fk_caisse integer,
  fk_session integer,
  previous_session_status integer,
  fk_das integer,
  fk_user_cashier integer,
  fk_user_controller integer NOT NULL,
  trigger_type varchar(64) NOT NULL,
  date_start datetime NOT NULL,
  date_end datetime,
  freeze_enabled integer DEFAULT 0,
  theoretical_amount double(24,8) DEFAULT 0,
  physical_amount double(24,8) DEFAULT 0,
  gap_amount double(24,8) DEFAULT 0,
  observations text,
  cashier_signature_status varchar(64),
  controller_signature_ref varchar(255),
  cashier_signature_ref varchar(255),
  report_ref varchar(255),
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_caisse_validation (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64),
  object_type varchar(128) NOT NULL,
  object_id integer NOT NULL,
  workflow_code varchar(128),
  validation_level integer DEFAULT 1 NOT NULL,
  validation_mode varchar(64) DEFAULT 'sequential',
  fk_user_requester integer,
  fk_user_validator integer,
  role_required varchar(64),
  decision varchar(64),
  decision_reason text,
  date_request datetime NOT NULL,
  date_decision datetime,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_caisse_transfert (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_agence integer NOT NULL,
  fk_caisse_source integer NOT NULL,
  fk_caisse_dest integer,
  fk_session_source integer,
  transfer_type varchar(64) DEFAULT 'vault',
  amount double(24,8) DEFAULT 0 NOT NULL,
  currency_code varchar(10),
  detail_coupures text,
  fk_user_sender integer,
  fk_user_receiver integer,
  transfer_reason text,
  attachment_ref varchar(255),
  signature_ref varchar(255),
  date_transfer datetime NOT NULL,
  date_receive datetime,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_caisse_depot_banque (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_agence integer NOT NULL,
  fk_caisse_source integer,
  fk_session integer,
  fk_bank_account integer,
  fk_bank integer,
  amount double(24,8) DEFAULT 0 NOT NULL,
  currency_code varchar(10),
  date_preparation datetime,
  date_deposit datetime,
  date_reconcile datetime,
  fk_user_depositor integer,
  fk_user_validator integer,
  bank_slip_number varchar(128),
  bank_slip_scan_ref varchar(255),
  reconcile_reference varchar(128),
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_caisse_workflow (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  code varchar(128) NOT NULL,
  label varchar(255) NOT NULL,
  object_type varchar(128) NOT NULL,
  agency_scope varchar(255),
  das_scope varchar(255),
  payment_mode_scope varchar(255),
  min_amount double(24,8) DEFAULT 0,
  max_amount double(24,8) DEFAULT 0,
  risk_level varchar(64),
  rule_expression text,
  validation_steps text,
  status integer DEFAULT 1 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_caisse_alerte (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64),
  dedup_key varchar(255),
  alert_type varchar(128) NOT NULL,
  severity varchar(64) DEFAULT 'info',
  fk_agence integer,
  fk_caisse integer,
  fk_session integer,
  object_type varchar(128),
  object_id integer,
  message text NOT NULL,
  target_roles text,
  date_alert datetime NOT NULL,
  date_read datetime,
  date_close datetime,
  fk_user_read integer,
  fk_user_close integer,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_mapping_comptable (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  code varchar(128) NOT NULL,
  operation_type varchar(128) NOT NULL,
  fk_agence integer,
  fk_das integer,
  payment_mode varchar(64),
  journal_code varchar(32),
  account_debit varchar(64),
  account_credit varchar(64),
  analytic_code varchar(128),
  rule_expression text,
  status integer DEFAULT 1 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);
