-- Dolibarr object enrichment/link tables.
-- These tables avoid duplicating Dolibarr standard objects.

CREATE TABLE llx_sof_facture_link (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_facture integer NOT NULL,
  fk_soc integer,
  fk_agence integer,
  fk_caisse integer,
  fk_session integer,
  fk_das integer,
  source_type varchar(64),
  source_id integer,
  billing_status integer DEFAULT 0,
  deferred_status integer DEFAULT 0,
  accounting_status integer DEFAULT 0,
  note_private text,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_paiement_link (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_paiement integer NOT NULL,
  fk_facture integer,
  fk_bank integer,
  fk_soc integer,
  fk_agence integer,
  fk_caisse integer,
  fk_session integer,
  fk_das integer,
  payment_component_type varchar(64) DEFAULT 'real',
  payment_mode varchar(64),
  amount double(24,8) DEFAULT 0 NOT NULL,
  transaction_ref varchar(128),
  transaction_date datetime,
  payer_name varchar(255),
  operator_name varchar(255),
  justification_ref varchar(255),
  reconcile_status integer DEFAULT 0,
  status integer DEFAULT 1 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_commande_link (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_commande integer NOT NULL,
  fk_soc integer,
  fk_agence integer,
  fk_caisse integer,
  fk_session integer,
  fk_das integer,
  source_type varchar(64),
  source_id integer,
  deferred_payment_status integer DEFAULT 0,
  invoice_status integer DEFAULT 0,
  note_private text,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_takepos_link (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  terminal_ref varchar(64) NOT NULL,
  fk_agence integer NOT NULL,
  fk_caisse integer NOT NULL,
  fk_session integer,
  fk_facture integer,
  fk_das integer,
  place_ref varchar(64),
  ticket_ref varchar(128),
  pos_source varchar(64),
  billing_status integer DEFAULT 0,
  reconcile_status integer DEFAULT 0,
  status integer DEFAULT 1 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_avoir_tracking (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_facture_avoir integer NOT NULL,
  fk_facture_origin integer,
  fk_soc integer NOT NULL,
  fk_agence integer,
  fk_session integer,
  fk_das integer,
  initial_amount double(24,8) DEFAULT 0 NOT NULL,
  used_amount double(24,8) DEFAULT 0,
  remaining_amount double(24,8) DEFAULT 0,
  reason text,
  expiration_date date,
  validation_status integer DEFAULT 0,
  date_validation datetime,
  fk_user_validator integer,
  use_status integer DEFAULT 0,
  date_last_use datetime,
  fk_user_last_use integer,
  blocked_reason text,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_bank_link (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_bank integer NOT NULL,
  fk_bank_account integer,
  fk_agence integer,
  fk_caisse integer,
  fk_session integer,
  fk_depot_banque integer,
  operation_type varchar(64),
  reconcile_status integer DEFAULT 0,
  accounting_status integer DEFAULT 0,
  note_private text,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_product_das (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_product integer NOT NULL,
  fk_das integer NOT NULL,
  fk_agence integer,
  payment_modes_allowed text,
  deferred_payment_allowed integer DEFAULT 0,
  refund_rules text,
  credit_note_rules text,
  accountancy_code varchar(64),
  analytic_code varchar(128),
  status integer DEFAULT 1 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_tiers_credit_profile (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_soc integer NOT NULL,
  fk_agence_followup integer,
  deferred_payment_allowed integer DEFAULT 0,
  credit_limit double(24,8) DEFAULT 0,
  payment_delay_days integer DEFAULT 0,
  risk_status varchar(64),
  blocked_status integer DEFAULT 0,
  surveillance_status integer DEFAULT 0,
  fk_user_sales_responsible integer,
  incident_history text,
  validation_rules text,
  status integer DEFAULT 1 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);
