-- Deferred-payment supports and receivable follow-up.
-- These objects are not real payments; they must lead to Dolibarr invoices and later Dolibarr payments.

CREATE TABLE llx_sof_bon_commande_client (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_soc integer NOT NULL,
  fk_contact_signatory integer,
  fk_agence integer,
  fk_das integer,
  fk_commande integer,
  fk_facture integer,
  order_number varchar(128) NOT NULL,
  order_date date,
  authorized_amount double(24,8) DEFAULT 0 NOT NULL,
  consumed_amount double(24,8) DEFAULT 0,
  remaining_amount double(24,8) DEFAULT 0,
  object_label varchar(255),
  service_description text,
  validity_start date,
  validity_end date,
  payment_due_date date,
  attachment_ref varchar(255),
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_bst (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  bst_number varchar(128) NOT NULL,
  bst_date date,
  issuer varchar(255),
  beneficiary varchar(255),
  fk_soc_payer integer NOT NULL,
  fk_contact_beneficiary integer,
  fk_agence integer,
  fk_das integer,
  fk_user_agent integer,
  fk_commande integer,
  fk_facture integer,
  route_or_service text,
  estimated_amount double(24,8) DEFAULT 0,
  final_amount double(24,8) DEFAULT 0,
  billing_conditions text,
  attachment_ref varchar(255),
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_instruction_manageriale (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  instruction_ref varchar(128) NOT NULL,
  fk_user_issuer integer,
  issuer_function varchar(128),
  instruction_date datetime,
  fk_soc integer,
  fk_contact integer,
  fk_agence integer,
  fk_das integer,
  fk_commande integer,
  fk_facture integer,
  service_description text,
  reason text,
  estimated_amount double(24,8) DEFAULT 0,
  final_amount double(24,8) DEFAULT 0,
  urgency_level varchar(64),
  attachment_ref varchar(255),
  fk_user_final_validator integer,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_paiement_differe (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_soc integer NOT NULL,
  fk_agence integer,
  fk_caisse integer,
  fk_session integer,
  fk_das integer,
  source_type varchar(64) NOT NULL,
  source_id integer,
  fk_facture integer,
  fk_commande integer,
  operation_date datetime,
  service_description text,
  expected_amount double(24,8) DEFAULT 0 NOT NULL,
  invoiced_amount double(24,8) DEFAULT 0,
  paid_amount double(24,8) DEFAULT 0,
  remaining_amount double(24,8) DEFAULT 0,
  expected_payment_date date,
  last_reminder_date date,
  dispute_reason text,
  date_validation datetime,
  fk_user_validator integer,
  date_dispute datetime,
  fk_user_dispute integer,
  regularization_reason text,
  date_regularization datetime,
  fk_user_regularization integer,
  closure_reason text,
  date_closure datetime,
  fk_user_closure integer,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);
