-- Industrial operations: notifications, imports, collections, retries, reversals and retention.

CREATE TABLE llx_sof_notification_config (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  event_code varchar(128) NOT NULL,
  severity_min varchar(32) DEFAULT 'info' NOT NULL,
  channel varchar(32) NOT NULL,
  recipient_type varchar(32) DEFAULT 'address' NOT NULL,
  recipient varchar(255) NOT NULL,
  escalation_level integer DEFAULT 0 NOT NULL,
  status integer DEFAULT 1 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer
);

CREATE TABLE llx_sof_notification_outbox (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  dedup_key varchar(255),
  event_code varchar(128) NOT NULL,
  severity varchar(32) DEFAULT 'info' NOT NULL,
  channel varchar(32) NOT NULL,
  recipient varchar(255) NOT NULL,
  subject varchar(255) NOT NULL,
  body text NOT NULL,
  object_type varchar(128),
  object_id integer,
  fk_agence integer,
  escalation_level integer DEFAULT 0 NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  max_attempts integer DEFAULT 5 NOT NULL,
  next_attempt datetime,
  date_sent datetime,
  last_error text,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer
);

CREATE TABLE llx_sof_bank_import (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  source_type varchar(32) NOT NULL,
  fk_bank_account integer,
  fk_agence integer,
  original_filename varchar(255) NOT NULL,
  file_checksum varchar(128) NOT NULL,
  statement_start date,
  statement_end date,
  currency_code varchar(10),
  total_amount double(24,8) DEFAULT 0,
  line_count integer DEFAULT 0 NOT NULL,
  matched_count integer DEFAULT 0 NOT NULL,
  suggested_count integer DEFAULT 0 NOT NULL,
  error_count integer DEFAULT 0 NOT NULL,
  status integer DEFAULT 0 NOT NULL,
  date_import datetime NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer
);

CREATE TABLE llx_sof_bank_import_line (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_import integer NOT NULL,
  line_number integer NOT NULL,
  external_ref varchar(255),
  operation_date date NOT NULL,
  value_date date,
  amount double(24,8) NOT NULL,
  currency_code varchar(10),
  counterparty varchar(255),
  description text,
  payment_mode varchar(32),
  fk_bank integer,
  fk_depot_banque integer,
  fk_mouvement integer,
  fk_paiement integer,
  match_score integer DEFAULT 0 NOT NULL,
  match_reason text,
  date_reconcile datetime,
  fk_user_reconcile integer,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer
);

CREATE TABLE llx_sof_recouvrement (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_paiement_differe integer,
  fk_facture integer,
  fk_soc integer NOT NULL,
  fk_agence integer,
  assigned_user integer,
  stage varchar(64) DEFAULT 'new' NOT NULL,
  priority varchar(32) DEFAULT 'normal' NOT NULL,
  outstanding_amount double(24,8) DEFAULT 0 NOT NULL,
  next_action_date date,
  last_contact_date datetime,
  promise_date date,
  promise_amount double(24,8),
  dispute_reason text,
  closure_reason text,
  status integer DEFAULT 0 NOT NULL,
  date_open datetime NOT NULL,
  date_close datetime,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer
);

CREATE TABLE llx_sof_recouvrement_action (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_recouvrement integer NOT NULL,
  action_type varchar(64) NOT NULL,
  channel varchar(32),
  outcome varchar(64),
  notes text NOT NULL,
  next_action_date date,
  date_action datetime NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer
);

CREATE TABLE llx_sof_bulk_import (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  object_type varchar(32) NOT NULL,
  import_mode varchar(32) DEFAULT 'upsert' NOT NULL,
  original_filename varchar(255) NOT NULL,
  file_checksum varchar(128) NOT NULL,
  line_count integer DEFAULT 0 NOT NULL,
  created_count integer DEFAULT 0 NOT NULL,
  updated_count integer DEFAULT 0 NOT NULL,
  error_count integer DEFAULT 0 NOT NULL,
  status integer DEFAULT 0 NOT NULL,
  date_start datetime NOT NULL,
  date_end datetime,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer
);

CREATE TABLE llx_sof_bulk_import_line (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_import integer NOT NULL,
  line_number integer NOT NULL,
  external_key varchar(255),
  payload text,
  target_object_id integer,
  action_taken varchar(32),
  error_message text,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer
);

CREATE TABLE llx_sof_technical_error (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  operation_code varchar(128) NOT NULL,
  retry_handler varchar(64),
  object_type varchar(128),
  object_id integer,
  payload text,
  error_class varchar(255),
  error_message text NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  max_attempts integer DEFAULT 3 NOT NULL,
  next_retry datetime,
  date_last_attempt datetime,
  date_resolution datetime,
  resolution_note text,
  fk_user_resolution integer,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer
);

CREATE TABLE llx_sof_financial_reversal (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_mouvement_original integer NOT NULL,
  fk_mouvement_reversal integer,
  reason text NOT NULL,
  evidence_ref varchar(255),
  fk_user_request integer NOT NULL,
  fk_user_approval integer,
  date_request datetime NOT NULL,
  date_decision datetime,
  decision_reason text,
  status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer
);

CREATE TABLE llx_sof_archive_log (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  object_type varchar(128) NOT NULL,
  object_id integer,
  document_path varchar(1024),
  archive_path varchar(1024),
  content_hash varchar(128),
  policy_code varchar(64) NOT NULL,
  action_type varchar(32) NOT NULL,
  reason text,
  action_date datetime NOT NULL,
  fk_user_action integer,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer
);
