ALTER TABLE llx_sof_notification_config ADD UNIQUE INDEX uk_sof_notif_config (entity, event_code, channel, recipient, escalation_level);
ALTER TABLE llx_sof_notification_config ADD INDEX idx_sof_notif_config_status (entity, status);
ALTER TABLE llx_sof_notification_outbox ADD UNIQUE INDEX uk_sof_notif_outbox_ref (entity, ref);
ALTER TABLE llx_sof_notification_outbox ADD UNIQUE INDEX uk_sof_notif_outbox_dedup (entity, dedup_key);
ALTER TABLE llx_sof_notification_outbox ADD INDEX idx_sof_notif_outbox_queue (entity, status, next_attempt);
ALTER TABLE llx_sof_bank_import ADD UNIQUE INDEX uk_sof_bank_import_ref (entity, ref);
ALTER TABLE llx_sof_bank_import ADD UNIQUE INDEX uk_sof_bank_import_checksum (entity, source_type, file_checksum);
ALTER TABLE llx_sof_bank_import_line ADD UNIQUE INDEX uk_sof_bank_import_line (entity, fk_import, line_number);
ALTER TABLE llx_sof_bank_import_line ADD UNIQUE INDEX uk_sof_bank_import_line_bank (entity, fk_bank);
ALTER TABLE llx_sof_bank_import_line ADD UNIQUE INDEX uk_sof_bank_import_line_movement (entity, fk_mouvement);
ALTER TABLE llx_sof_bank_import_line ADD INDEX idx_sof_bank_import_match (entity, status, amount, operation_date);
ALTER TABLE llx_sof_recouvrement ADD UNIQUE INDEX uk_sof_recouvrement_ref (entity, ref);
ALTER TABLE llx_sof_recouvrement ADD UNIQUE INDEX uk_sof_recouvrement_deferred (entity, fk_paiement_differe);
ALTER TABLE llx_sof_recouvrement ADD INDEX idx_sof_recouvrement_queue (entity, status, next_action_date);
ALTER TABLE llx_sof_recouvrement_action ADD INDEX idx_sof_recouvrement_action_case (entity, fk_recouvrement, date_action);
ALTER TABLE llx_sof_bulk_import ADD UNIQUE INDEX uk_sof_bulk_import_ref (entity, ref);
ALTER TABLE llx_sof_bulk_import ADD UNIQUE INDEX uk_sof_bulk_import_checksum (entity, object_type, file_checksum);
ALTER TABLE llx_sof_bulk_import_line ADD UNIQUE INDEX uk_sof_bulk_import_line (entity, fk_import, line_number);
ALTER TABLE llx_sof_technical_error ADD UNIQUE INDEX uk_sof_technical_error_ref (entity, ref);
ALTER TABLE llx_sof_technical_error ADD INDEX idx_sof_technical_error_retry (entity, status, next_retry);
ALTER TABLE llx_sof_financial_reversal ADD UNIQUE INDEX uk_sof_financial_reversal_ref (entity, ref);
ALTER TABLE llx_sof_financial_reversal ADD UNIQUE INDEX uk_sof_financial_reversal_original (entity, fk_mouvement_original);
ALTER TABLE llx_sof_archive_log ADD UNIQUE INDEX uk_sof_archive_log_ref (entity, ref);
ALTER TABLE llx_sof_archive_log ADD INDEX idx_sof_archive_log_object (entity, object_type, object_id);
