-- Operational ledger and refund workflow for the Agence module.
-- Real invoices, payments, credit notes and bank lines remain owned by Dolibarr.

CREATE TABLE llx_sof_caisse_mouvement (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_agence integer NOT NULL,
  fk_caisse integer NOT NULL,
  fk_session integer NOT NULL,
  fk_das integer,
  fk_soc integer,
  fk_facture integer,
  fk_paiement integer,
  fk_payment_various integer,
  fk_bank integer,
  type_operation varchar(64) NOT NULL,
  direction varchar(16) NOT NULL,
  payment_mode varchar(64),
  amount double(24,8) DEFAULT 0 NOT NULL,
  transaction_date datetime NOT NULL,
  source_type varchar(64),
  source_id integer,
  transaction_ref varchar(128),
  label varchar(255),
  justification_ref varchar(255),
  status integer DEFAULT 1 NOT NULL,
  accounting_status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);

CREATE TABLE llx_sof_remboursement (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  ref varchar(64) NOT NULL,
  fk_soc integer NOT NULL,
  fk_agence integer,
  fk_das integer,
  fk_caisse integer,
  fk_session integer,
  fk_facture_origin integer,
  fk_paiement_origin integer,
  fk_mouvement_origin integer,
  fk_facture_avoir integer,
  fk_payment_various integer,
  requested_amount double(24,8) DEFAULT 0 NOT NULL,
  approved_amount double(24,8) DEFAULT 0,
  refunded_amount double(24,8) DEFAULT 0,
  payment_mode varchar(64),
  reason text NOT NULL,
  request_date datetime NOT NULL,
  validation_date datetime,
  execution_date datetime,
  fk_user_requester integer NOT NULL,
  fk_user_validator integer,
  fk_user_executor integer,
  rejection_reason text,
  status integer DEFAULT 0 NOT NULL,
  accounting_status integer DEFAULT 0 NOT NULL,
  date_creation datetime NOT NULL,
  tms timestamp,
  fk_user_creat integer NOT NULL,
  fk_user_modif integer,
  import_key varchar(14)
);
